# Generated by Django 4.0 on 2023-02-17 12:22

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=60)),
                ('Farge', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'verbose_name_plural': 'Statuser',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emne', models.CharField(max_length=100)),
                ('Sender_epost', models.EmailField(max_length=100)),
                ('Sender_navn', models.CharField(max_length=100)),
                ('Melding', models.TextField(max_length=2000)),
                ('Dato_lagd', models.DateTimeField()),
                ('Status', models.ForeignKey(blank=True, default=ticket.models.get_default_status, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.status')),
                ('Tildelt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
                ('Tildelt_avdeling', models.ForeignKey(blank=True, default=ticket.models.get_default_avdeling, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
        ),
    ]
