# Generated by Django 4.0 on 2023-02-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avdeling',
            options={'verbose_name_plural': 'Avdelinger'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuser'},
        ),
        migrations.AlterModelOptions(
            name='teknikker',
            options={'verbose_name_plural': 'Teknikkere'},
        ),
    ]
