# Generated by Django 4.0 on 2023-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Dato_lagd',
            field=models.DateField(auto_now_add=True),
        ),
    ]
