# Generated by Django 4.0 on 2023-02-16 12:35

from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_avdeling_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Status',
            field=models.ForeignKey(blank=True, default=ticket.models.get_default_status, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Tildelt_avdeling',
            field=models.ForeignKey(blank=True, default=ticket.models.get_default_avdeling, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.avdeling'),
        ),
    ]
