# Generated by Django 4.0 on 2023-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_dato_lukket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Sender_status',
            field=models.CharField(choices=[('PRIVAT', 'PRIVAT'), ('BEDRIFT', 'BEDRIFT')], default='PRIVAT', max_length=255),
        ),
    ]
