# Generated by Django 4.0 on 2023-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_sender_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Sender_status',
            field=models.CharField(choices=[('PRIVAT', 'privat'), ('BEDRIFT', 'bedrift')], default='PRIVAT', max_length=255),
        ),
    ]
